"use client";
import {useEffect,useState} from "react";
export default function Admin(){
 const [password,setPassword]=useState(""); const [logged,setLogged]=useState(false); const [keys,setKeys]=useState<any[]>([]); const [msg,setMsg]=useState("");
 async function login(){const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})}); if(r.ok){setLogged(true);load()}else setMsg("Sai mật khẩu quản trị.")}
 async function load(){const r=await fetch("/api/admin/keys"); if(r.ok){const d=await r.json();setKeys(d.keys.map((x:any)=>({...x,key:""})));}}
 function change(i:number,field:string,value:any){setKeys(a=>a.map((x,j)=>j===i?{...x,[field]:value}:x))}
 async function save(){const payload=keys.filter(k=>k.key?.trim()).map(k=>({provider:k.provider,key:k.key,enabled:k.enabled!==false})); const r=await fetch("/api/admin/keys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keys:payload})}); const d=await r.json();setMsg(r.ok?`Đã lưu ${d.count} API key.`:d.error)}
 if(!logged)return <main className="shell admin"><div className="nav"><div className="brand">MC <span>Translate</span> Studio</div><a href="/">Trang chủ</a></div><div className="panel" style={{padding:28}}><div className="eyebrow">Admin</div><h1>AI Provider Pool</h1><p className="muted">Chỉ chủ website nhập API. Key không được gửi xuống trình duyệt sau khi lưu.</p><input className="field" style={{padding:12,width:"100%",margin:"20px 0",background:"#08192b",border:"1px solid #20364e",color:"#fff",borderRadius:10}} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu admin"/><button className="button primary" onClick={login}>Đăng nhập</button><div className="status">{msg}</div></div></main>;
 return <main className="shell admin"><div className="nav"><div className="brand">MC <span>Translate</span> Studio</div><a href="/">Trang dịch</a></div><div className="panel" style={{padding:28}}><div className="eyebrow">AI Control Center</div><h1>20 API slots</h1><p className="muted">Mỗi slot chọn Gemini hoặc Groq. Hệ thống server-side xoay vòng các key đã bật.</p><div className="rows">{Array.from({length:20},(_,i)=>{const k=keys[i]||{id:i+1,provider:"gemini",key:"",enabled:true};return <div className="keyrow" key={i}><strong>#{String(i+1).padStart(2,"0")}</strong><select value={k.provider} onChange={e=>change(i,"provider",e.target.value)}><option value="gemini">Gemini</option><option value="groq">Groq</option></select><input type="password" value={k.key} onChange={e=>change(i,"key",e.target.value)} placeholder="Dán API key mới"/><label><input type="checkbox" checked={k.enabled!==false} onChange={e=>change(i,"enabled",e.target.checked)}/> Bật</label></div>})}</div><div className="actions"><button className="button primary" onClick={save}>Lưu API pool</button></div><div className="status">{msg}</div></div></main>
}