"use client";
import{useEffect,useState}from"react";
export default function Admin(){
 const[password,setPassword]=useState(""),[logged,setLogged]=useState(false),[keys,setKeys]=useState<any[]>([]),[status,setStatus]=useState<any[]>([]),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/admin/keys");if(r.ok){const d=await r.json();setLogged(true);setKeys(d.keys.map((x:any)=>({...x,key:""})));}const s=await fetch("/api/admin/pool");if(s.ok)setStatus((await s.json()).keys);}
 async function login(){const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setMsg("Sai mật khẩu quản trị.")}
 useEffect(()=>{load().catch(()=>{});},[]);
 function change(i:number,field:string,value:any){setKeys(a=>a.map((x,j)=>j===i?{...x,[field]:value}:x))}
 async function save(){const r=await fetch("/api/admin/keys",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({keys:keys.map(k=>({id:k.id,provider:k.provider,key:k.key||undefined,enabled:k.enabled!==false}))})});const d=await r.json();setMsg(r.ok?"Đã lưu API pool.":d.error||"Không thể lưu.");load();}
 if(!logged)return <main className="shell admin"><div className="nav"><div className="brand">MC <span>Translate</span> Studio</div><a href="/">Trang chủ</a></div><div className="panel" style={{padding:28}}><div className="eyebrow">Admin</div><h1>AI Provider Pool</h1><p className="muted">20 slot Gemini/Groq. Key được xử lý server-side.</p><input style={{padding:12,width:"100%",margin:"20px 0",background:"#08192b",border:"1px solid #20364e",color:"#fff",borderRadius:10}} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu admin"/><button className="button primary" onClick={login}>Đăng nhập</button><div className="status">{msg}</div></div></main>;
 return <main className="shell admin"><div className="nav"><div className="brand">MC <span>Translate</span> Studio</div><a href="/">Trang dịch</a></div><div className="panel" style={{padding:28}}><div className="eyebrow">AI Control Center</div><h1>20 API slots</h1><p className="muted">Round-robin theo thời gian sử dụng, tự cooldown khi 429/quota hoặc lỗi.</p><div className="rows">{Array.from({length:20},(_,i)=>{const k=keys[i]||{id:undefined,provider:"gemini",key:"",enabled:true};const s=status.find(x=>x.id===k.id);const cool=s&&s.cooldownUntil>Date.now();return <div className="keyrow" key={i}><strong>#{String(i+1).padStart(2,"0")}</strong><select value={k.provider} onChange={e=>change(i,"provider",e.target.value)}><option value="gemini">Gemini</option><option value="groq">Groq</option></select><input type="password" value={k.key} onChange={e=>change(i,"key",e.target.value)} placeholder={k.id?"Key đang lưu — nhập để thay":"Dán API key"}/><span className="muted">{cool?"Cooldown":s?.failures?(`Lỗi ${s.failures}`):"Ready"}</span><label><input type="checkbox" checked={k.enabled!==false} onChange={e=>change(i,"enabled",e.target.checked)}/> Bật</label></div>})}</div><div className="actions"><button className="button primary" onClick={save}>Lưu API pool</button><button className="button" onClick={load}>Làm mới trạng thái</button></div><div className="status">{msg}</div></div></main>}